language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"

before_install:
    - sh tests/start-neo4j-2.0.0.sh

install:
    - pip install -q coveralls --use-mirrors
    - pip install flake8

before_script:
    - flake8 graphlib

script:
    - coverage run test_suite.py

after_success:
    - coveralls
